<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Certificate — {{ $registration->name }}</title>
<style>
@font-face{font-family:'Dancing Script';font-style:normal;font-weight:400;src:url('/fonts/DancingScript-Regular.ttf') format('truetype')}
*{box-sizing:border-box}body{margin:0;background:#eef1f4;color:#172033;font-family:Arial,sans-serif}.toolbar{display:flex;justify-content:center;gap:10px;padding:18px}.toolbar a,.toolbar button{padding:10px 17px;border:0;border-radius:8px;background:#172033;color:white;text-decoration:none;cursor:pointer}.certificate{position:relative;width:min(1120px,calc(100vw - 32px));aspect-ratio:1.414/1;margin:0 auto 30px;overflow:hidden;background:#fffdf8;box-shadow:0 18px 55px #17203322}.frame{position:absolute;inset:18px;border:2px solid #c99a3b}.frame:after{content:"";position:absolute;inset:8px;border:1px solid #d9c394}.corner{position:absolute;width:155px;height:155px;background:#172033;transform:rotate(45deg)}.c1{left:-92px;top:-92px}.c2{right:-92px;bottom:-92px}.content{position:absolute;inset:8% 10%;display:flex;align-items:center;flex-direction:column;text-align:center}.brand{font-size:16px;font-weight:900;letter-spacing:.3em}.brand span{color:#c58b25}.kicker{margin-top:8%;color:#a97825;font-size:13px;font-weight:800;letter-spacing:.28em;text-transform:uppercase}.content h1{margin:2.5% 0 1%;font-family:Georgia,serif;font-size:clamp(38px,5vw,72px);font-weight:400;letter-spacing:.02em}.rule{width:90px;height:2px;background:#c99a3b}.presented{margin:2.5% 0 1%;color:#647083;font-family:Georgia,serif;font-size:16px;font-style:italic}.name{padding:0 30px 8px;border-bottom:1px solid #c99a3b;font-family:Georgia,serif;font-size:clamp(30px,4vw,55px);font-style:italic;color:#9a6819}.statement{max-width:720px;margin:2% auto 0;color:#4e5969;font-family:Georgia,serif;font-size:clamp(14px,1.8vw,21px);line-height:1.55}.statement strong{color:#172033}.details{display:flex;justify-content:center;gap:8%;width:100%;margin-top:auto}.detail{min-width:180px}.detail b{display:block;padding-bottom:7px;border-bottom:1px solid #9aa2ad;font-family:Georgia,serif;font-size:18px}.detail span{display:block;margin-top:7px;color:#7b8492;font-size:9px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.signature b{font-family:'Dancing Script',"Brush Script MT",cursive;font-size:27px;font-weight:400}.code{position:absolute;right:4%;bottom:4%;color:#6b7280;font-size:9px;letter-spacing:.08em}.invalid{position:absolute;z-index:3;inset:42% 15%;padding:20px;border:5px solid #b91c1c;color:#b91c1c;background:#fff8;font-size:38px;font-weight:900;transform:rotate(-8deg);text-align:center}@media(max-width:700px){.certificate{aspect-ratio:auto;min-height:700px}.content{inset:9%}.details{gap:20px;flex-wrap:wrap}.statement{font-size:16px}}@media print{body{background:white}.toolbar{display:none}.certificate{width:100%;height:100vh;margin:0;box-shadow:none}@page{size:A4 landscape;margin:0}}
.qr{position:absolute;right:4%;bottom:3%;width:82px;text-align:center;color:#6b7280;font-size:7px}.qr img{display:block;width:72px;height:72px;margin:auto}
</style></head><body>
<div class="toolbar"><a href="{{ route('certificates.download',$registration->certificate_code) }}">Download PDF</a><button onclick="window.print()">Print</button><a href="{{ route('certificates.verify',['code'=>$registration->certificate_code]) }}">Verify certificate</a></div>
<main class="certificate"><div class="frame"></div><i class="corner c1"></i><i class="corner c2"></i>
@if($registration->certificate_revoked_at)<div class="invalid">REVOKED</div>@endif
<div class="content"><div class="brand">STARMAX<span>.</span></div><div class="kicker">Certificate of Completion</div><h1>Achievement Recognized</h1><div class="rule"></div><p class="presented">This certificate is proudly presented to</p><div class="name">{{ $registration->name }}</div>
<p class="statement">{!! $registration->event->certificateMessageHtml($registration->company) !!}</p>
<div class="details"><div class="detail"><b>{{ $registration->event->starts_at?->format('F j, Y') }}</b><span>Date completed</span></div><div class="detail signature"><b>{{ $registration->event->certificate_signer_name ?: 'Starmax Team' }}</b><span>{{ $registration->event->certificate_signer_title ?: 'Authorized signature' }}</span></div><div class="detail"><b>{{ $registration->certificate_code }}</b><span>Certificate ID</span></div></div></div>
<div class="qr"><img src="{{ $qrCode }}" alt="Verification QR code">SCAN TO VERIFY</div></main></body></html>
